### ISSUE TITLE
跑来提个安装步骤plus

### ISSUE THREAD

**Issue by qhhuang** [lyw1995/Golang-Blog-Server#2]
看到要安装 redis 和 mysql 就都去装完了
homebrew下装新版的mysql 需要改密码权限 然后修改密码, 最后把config.toml里的密码修改成自己的
然后还需要登录 mysql -> CREATE DATABASE blog; 最后跑起来 输出的最后一行是
2019-04-23 14:00:15.4619 [DEBUG] [server.go:94] DotWeb:HttpServer ListenAndServe [:8888]
访问http://localhost:8888，页面显示{"code":4300,"msg":"资源不存在，或者访问了其他用户的资源。"}  就不知道该怎么做了  纯小白

**Comment by lyw1995** [comment]
不好意思,给您带来了不便.   过阵子我会把整理一下镜像,然后加上详细步骤 在把文档补齐,

**Comment by lyw1995** [comment]
@qhhuang 你跑起来的话, 看一下routers 里面的api定义,因为现在还没文档,
